### ISSUE TITLE
License is Missing

### ISSUE THREAD

**Issue by rlizzo** [TileDB-Inc/TileDB-Cloud-Py#40]
Just an FYI that there is no LICENSE file included in the master branch of the repo. 

This seems like an interesting project, looking forward to following it in the future!

**Comment by stavrospapadopoulos** [comment]
Thanks @rlizzo. Please let us know if you'd like some extra credit to try out TileDB Cloud (it gives you $10 upon sign up). Some more info below:

TileDB Cloud: https://console.tiledb.com/signup
Docs: https://docs.tiledb.com/cloud/

**Comment by rlizzo** [comment]
Thanks for the quick response and info @stavrospapadopoulos!

I love the new website / docs, but haven't had a chance to see the cloud console until now (just signed up)! I should have some time in the next few days to give it a shot.

After a quick look, I actually do have one fairly pertinent question... On the pricing page (https://docs.tiledb.com/cloud/pricing) I only see costs for data eggress and query time.  Is there really no charge for the storage of data in the tiledb cloud? It's a bit ambiguous right now.

**Comment by stavrospapadopoulos** [comment]
TileDB Cloud does not charge for storage, because every user must store their TileDB arrays in their own AWS S3 buckets (and of course pay separately for storage to AWS). You just _register_ your existing arrays to TileDB Cloud, and then you are able to share, slice and compute on them without unnecessary data copying or movement. I tried to clarify in the docs, thanks for bringing it up.

**Comment by rlizzo** [comment]
Ahh thanks for the clarification! Makes much more sense.
